name: test

on:
  push:
    branches:  [dev]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependencies install
        run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - name: dependencies install
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: dependencies install
        run: npm run deploy

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
